# Generated by Django 5.1.2 on 2024-10-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0002_remove_date_picture_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='date',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
