# Generated by Django 5.1.2 on 2024-10-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0003_date_description_date_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('dates', models.ManyToManyField(related_name='relationships', to='dates.date')),
                ('users', models.ManyToManyField(related_name='relationships', to='dates.user')),
            ],
        ),
    ]
