# Generated by Django 5.1.2 on 2024-10-14 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0006_alter_relationship_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='users',
        ),
    ]
