# Generated by Django 5.1.2 on 2024-10-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0007_remove_relationship_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='date',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='date_images/'),
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
