# Generated by Django 5.1.2 on 2024-10-17 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0008_remove_user_groups_remove_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date',
            name='images',
        ),
        migrations.CreateModel(
            name='DateImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='date_images/')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dates.date')),
            ],
        ),
    ]
